### ISSUE TITLE
Change legend text from "geoportal" to "-hosted data portal"

### ISSUE THREAD

**Issue by karenmajewicz** [YijingZhou33/BTAA_County_Map#1]
County Geoportal -> County-hosted Data Portal
City Geoportal -> City-hosted Data Portal

(The word "geoportal" is not commonly used outside of a few projects, so I think this wording might be more accurate)

**Comment by YijingZhou33** [comment]
Changed "geoportal" in legend, layer filter and title.
Is "Big Ten Academic Alliance County-hosted & City-hosted Data Portals" a proper title? Maybe too long?

**Comment by karenmajewicz** [comment]
Maybe it could be something like:
Title: 
Subtitle: Big Ten Academic Alliance Region

title ideas:
Open Geodata from Counties & Cities
Available City and County GIS Data
Free and Open Geospatial Data
Data Portals Hosted by Counties & Cities
Counties & Cities with Free & Open GIS Data

hmmm...

**Comment by YijingZhou33** [comment]
Randomly chose 1 title - We can change it anytime. 
Also added the logo. 
![image](https://user-images.githubusercontent.com/66186715/103568378-56624b80-4ebd-11eb-878f-a8fb9c0be6d2.png)
