### ISSUE TITLE
Change popup text to be more descriptive

### ISSUE THREAD

**Issue by karenmajewicz** [YijingZhou33/BTAA_County_Map#2]
Example using Washington County, Minnesota:

Top link could be: "Browse Washington County geospatial datasets"

Bottom could be: "Visit Washington County Open Data website"

**Comment by YijingZhou33** [comment]
**County data portal popup:**
![image](https://user-images.githubusercontent.com/66186715/103566144-15e7db00-4e87-11eb-854a-1fd86a965f9d.png)

**City data portal popup:**
![image](https://user-images.githubusercontent.com/66186715/103566198-2f892280-4e87-11eb-81a9-7150a0ad8994.png)

**Comment by karenmajewicz** [comment]
Minor spelling:

For County, fix spelling to "geospatial" instead of "geopsatial"

For City, fix spelling to "Browse" instead of "Browser"

**Comment by YijingZhou33** [comment]
Oops... Too focused on my ice cream, have already got it right!

**Comment by karenmajewicz** [comment]
The number of records listed next to the county under the dropdown menu is very cool. Could this be added to the text in the popup for the Browse....?

Also, could we add an icon to the Visit xxx website? Something that makes it clear the user would be visiting a new site. (https://www.google.com/search?q=external+link+icon)

**Comment by karenmajewicz** [comment]
The map is looking great!

I don't know if you have pushed all of your commits to the .io site, but I
noticed that the link for the "Browse xxx geospatial datasets" for the
COUNTIES doesn't seem to be configured. The cities are working fine.

-Karen
