### ISSUE TITLE
Add an About popup

### ISSUE THREAD

**Issue by karenmajewicz** [YijingZhou33/BTAA_County_Map#3]
Something like:

> This map displays the known counties and cities in the [BTAA Geoportal region](https://btaagdp.org/about) that publish open geospatial data. Additional portals and data are added regularly. To report missing data portals, [contact us here](https://btaagdp.org/feedback).

> Click on a county or city to browse the records in the BTAA Geoportal and to visit the source website.  Use the menu at the top to filter the map display.

**Comment by karenmajewicz** [comment]
I get a lot of questions about why certain sites aren't included in this map, so maybe we can also put this in the About page:

> For inclusion in this map, the data must:
> 1. have an open license or open status
> 2. be accessible for free 
> 3. be downloadable as discrete layers and not just viewable from inside an online web map or database application
> 4. have been created or published by a city or county government entity

**Comment by YijingZhou33** [comment]
Added an "About" button on the navbar.

![image](https://user-images.githubusercontent.com/66186715/103593353-3df13180-4ebb-11eb-8c31-ff6d99f0589a.png)
